site_name: Dicas PJe - Justica Eleitoral
nav:
    - Home: 'index.md'
    - Dicas e DÃºvidas Frequentes: 'dicas.md'
plugins:
    - search:
        lang: pt
    - awesome-pages
    - mermaid2
    - exclude-search:
        exclude:
          - como_editar_pagina.md
theme:
  name: material
  language: pt
  icon:
    logo: material/lightbulb
  favicon: img/dicas.png
  features:
    - search.suggest
    - search.highlight
    - navigation.sections