site_name: Dicas PJe - Justica Eleitoral
nav:
    - Home: 'index.md'
    - Dicas e DÃºvidas Frequentes: 'dicas.md'
    - Priorizar Chamado: 'prioridade.md'
    - Participe!: 'participe.md'
plugins:
    - search:
        lang: pt
    - exclude-search:
        exclude:
          - como_editar_pagina.md
theme:
  name: material
  language: pt
  icon:
    logo: material/lightbulb
  favicon: img/dicas.png
  features:
    - search.suggest
    - search.highlight
    - navigation.sections
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - js/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
  - css/tse.css